### ISSUE TITLE
FastAPI production issues with a synchronous SQLAlchemy session

### ISSUE THREAD

**Issue by wolffparkinson** [ChristopherGS/ultimate-fastapi-tutorial#15]
Amazing blog series. Really helped a lot clear some basics about FastAPI.

I shifted my project from Flask to FastAPI and noticed some latency issues with database  calls
(earlier using Flask-SQLAlchemy) with MySQL.

Although FastAPI is faster than Flask in serving the requests, but when it comes to making the database calls, which eventually every production app would run into, using FastAPI with SQLAlchemy as a dependency injection or even as a middleware, especially with a Synchronous SQLAlchemy flavor does cause some troubles in production.

Thought you might wanna look into this before Dependency post comes out.
- [Using dependency injection to get SQLAlchemy session can lead to deadlock](https://github.com/tiangolo/fastapi/issues/3205)
- [sqlalchemy queue pool limit lockup/timeout](https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/104#issue-556642895)
- [benchmark between sync and async way using SQLAlchemy and FastAPI](https://github.com/andersonrocha0/fastApiAndSqlAlchemySyncVsAsync)

A common approach followed to use the new SQLAlchemy 1.4 by many is :
```python
engine_async = create_async_engine(SQLALCHEMY_DATABASE_URL)

async_session = sessionmaker(
    engine_async,
    expire_on_commit=False,
    autocommit=False,
    autoflush=False,
    class_=AsyncSession,
)

@app.get("/users/insert-data-to-test")
async def insert_data_to_test():
    async with async_session() as session:
        async with session.begin():
            user = User()
            user.email = "teste@teste.com.br"
            session.add(user)
            session.commit()
```

I know SQLAlchemy Async i.e. 1.4 is still in Alpha, but looks promising in terms of avoiding some production related issues with synchronous session.

Would love to hear your comments or analysis in upcoming episodes of the blog series.

**Comment by sandys** [comment]
I have a fully working, sqlalchemy and pydantic compatible gist here with both syncpg and asyncpg.

https://gist.github.com/sandys/671b8b86ba913e6436d4cb22d04b135f

You can try it and let me know. I have already benchmarked it. So should work fine.
